apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harness-ui
  template:
    metadata:
      labels:
        app: harness-ui
    spec:
      containers:
      - image: golang:1.17
        name: harness-ui
        ports:
        - containerPort: 80
